apiVersion: v1
kind: Secret
metadata:
  name: gobank-secrets
  labels:
    app: gobank
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: ""
  JWT_SECRET_KEY: "CHANGE_ME_TO_A_SECURE_RANDOM_STRING_IN_PRODUCTION"
